/// One row per calendar day, from the first to the last sales day. Marked as the date table.
table Date
	lineageTag: 14a5102b-56fb-4f10-8120-4ecfd4fdb0d3
	dataCategory: Time

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: a7fdad84-7e02-4b43-9195-4641e0740130
		summarizeBy: none
		sourceColumn: date_key

	column Date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: 258b0291-b08a-4632-86d6-629c928ab542
		summarizeBy: none
		sourceColumn: date

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 91f83c94-55e4-4f59-b74e-af7d5b993c60
		summarizeBy: none
		sourceColumn: year

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 976496e9-4622-451f-87b7-f242b7ddbc78
		summarizeBy: none
		sourceColumn: quarter

	column Month
		dataType: string
		lineageTag: efb6a1fb-0727-4228-9241-70e5458cfeb6
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: 'Month Number'

	column 'Month Number'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 693b1fe9-9fac-4e8f-8410-090d1bf59863
		summarizeBy: none
		sourceColumn: month_num

	column 'Year Month'
		dataType: string
		lineageTag: 4dcfa2a2-1675-463b-aba5-fe86d4807a3f
		summarizeBy: none
		sourceColumn: year_month
		sortByColumn: 'Month Key'

	column 'Month Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: da300576-c66a-42db-8f8d-08a11e972a31
		summarizeBy: none
		sourceColumn: month_key

	column 'ISO Week'
		dataType: int64
		formatString: 0
		lineageTag: 97e28ae0-a1d2-4abe-b442-331ca42823f2
		summarizeBy: none
		sourceColumn: iso_week

	column 'ISO Year'
		dataType: int64
		formatString: 0
		lineageTag: 5b04061e-50bd-4118-91b6-d2de155daac5
		summarizeBy: none
		sourceColumn: iso_year

	column Weekday
		dataType: string
		lineageTag: 2c511330-82e3-4fc4-9504-cf43c915d248
		summarizeBy: none
		sourceColumn: weekday_name
		sortByColumn: 'Weekday Number'

	column 'Weekday Number'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c181f154-3f06-4620-a7a6-614b913eae1c
		summarizeBy: none
		sourceColumn: weekday_num

	column 'Is Weekend'
		dataType: boolean
		lineageTag: f0f53ee8-b769-4f28-af32-c2e8e9d2ae0c
		summarizeBy: none
		sourceColumn: is_weekend

	column 'Is National Holiday'
		dataType: boolean
		lineageTag: abe59858-2ceb-4db2-b929-6f1324e7d31a
		summarizeBy: none
		sourceColumn: is_national_holiday

	/// Fiscal year: February to January, named by the calendar year it ends in (FY2017 = Feb 2016 – Jan 2017).
	column 'Fiscal Year'
		dataType: string
		summarizeBy: none
		sourceColumn: fiscal_year

	/// Fiscal quarter, Q1 = February to April.
	column 'Fiscal Quarter'
		dataType: string
		summarizeBy: none
		sourceColumn: fiscal_quarter

	/// Month name, sorted in fiscal order (February first).
	column 'Fiscal Month'
		dataType: string
		summarizeBy: none
		sourceColumn: fiscal_month
		sortByColumn: 'Fiscal Month Number'

	column 'Fiscal Month Number'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: fiscal_month_num

	/// Fiscal year → quarter → month → day, for drilling down on date axes and slicers.
	hierarchy 'Fiscal Calendar'

		level 'Fiscal Year'
			column: 'Fiscal Year'

		level 'Fiscal Quarter'
			column: 'Fiscal Quarter'

		level 'Fiscal Month'
			column: 'Fiscal Month'

		level Date
			column: Date

	partition Date = m
		mode: import
		source =
				let
				    Source = Sql.Database(SqlEndpoint, Lakehouse),
				    Data = Source{[Schema = "dbo", Item = "dim_date"]}[Data],
				    Selected = Table.SelectColumns(Data, {"date_key", "date", "year", "quarter", "month_num", "month_name", "month_key", "iso_week", "iso_year", "weekday_num", "weekday_name", "is_weekend", "is_national_holiday"}),
				    WithYearMonth = Table.AddColumn(Selected, "year_month", each Date.ToText([date], [Format = "MMM yyyy", Culture = "en-US"]), type text),
				    // fiscal year runs February to January and is named by the year it ends in
				    FiscalStartMonth = 2,
				    WithFiscalMonthNum = Table.AddColumn(WithYearMonth, "fiscal_month_num", each Number.Mod(Date.Month([date]) + 12 - FiscalStartMonth, 12) + 1, Int64.Type),
				    WithFiscalYear = Table.AddColumn(WithFiscalMonthNum, "fiscal_year", each "FY" & Text.From(Date.Year([date]) + (if Date.Month([date]) >= FiscalStartMonth then 1 else 0)), type text),
				    WithFiscalQuarter = Table.AddColumn(WithFiscalYear, "fiscal_quarter", each "Q" & Text.From(Number.RoundUp([fiscal_month_num] / 3)), type text),
				    Result = Table.AddColumn(WithFiscalQuarter, "fiscal_month", each Date.ToText([date], [Format = "MMM", Culture = "en-US"]), type text)
				in
				    Result

